### ISSUE TITLE
`:GoImpl` (without args) fails

### ISSUE THREAD

**Issue by ajitid** [mattn/vim-goimpl#1]
Given this code:

```go
type Foo interface {
     DoSomething()
}
```

If I put cursor on  `Foo` and type `:GoImpl` it throws:

```
couldn't parse interface: go-check.Foo 
```

---

Other commands like `:GoImpl Foo FooImpl` does work.

**Comment by ajitid** [comment]
Removing these lines made the plugin work:

https://github.com/mattn/vim-goimpl/blob/a18ec88cf5e8c4bd3177206416bc6fbd3c126a45/ftplugin/go/goimpl.vim#L15-L18

Tested with go version 1.17.6 linux/amd64:
- Ran `go mod init example.com/01`
- Created a dummy interface in a go file
- Ran `:GoImpl` command

**Comment by mattn** [comment]
Hmm, I don't reproduce it.

![screenshot](https://user-images.githubusercontent.com/10111/158067463-5526e910-25a7-4dd6-979a-a5c488d1cc26.gif)

**Comment by ajitid** [comment]
Can you confirm if I've installed the right package? I installed this way:

```sh
go install github.com/josharian/impl@latest
```

**Comment by ajitid** [comment]
This is really weird, it is working fine now, I have no idea what caused the issue.

Will re-open the ticket if I could encounter the issue again.
